import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sociedad-IA starter",
  description:
    "Reference Next.js app for an Argentine sociedad-IA operated by an LLM agent on top of @ar-agents/*. Generated by https://ar-agents.ar/incorporar.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body
        style={{
          margin: 0,
          fontFamily:
            "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        }}
      >
        {children}
      </body>
    </html>
  );
}
