// Generated by apps/landing/scripts/gen-discovery-manifests.mjs from
// packages/<name>/tools.manifest.json. Edit those files (via `pnpm regen-manifests`),
// not this one.
/* eslint-disable */
export const MANIFESTS = [
  {
    "package": "@ar-agents/aduana",
    "version": "0.1.0",
    "tools": [
      {
        "name": "aduana_lookup_despacho",
        "description": "Look up an Argentine customs declaration (consultar despacho aduanero) by its SUSI, KIM, or OM number. Returns current status (registrado / canalizado_verde / naranja / rojo / libre_disponibilidad / a",
        "input": {
          "kind": "SUSI | KIM | OM",
          "value": "string (number as printed on the despacho)"
        },
        "returns": "DespachoLookupResult",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      },
      {
        "name": "aduana_lookup_ncm",
        "description": "Look up an Argentine NCM tariff code (consultar posición arancelaria NCM). Returns the official description, whether it is currently in force, and its AEC (Mercosur common external tariff) + DIE (impo",
        "input": {
          "code": "8-digit NCM"
        },
        "returns": "NcmLookupResult | {code, found: false}",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/agentic-commerce-bridge",
    "version": "5.0.0",
    "description": "Open-source merchant facilitator for the Agentic Commerce Protocol (ACP). LLM-buyer-facing checkout sessions, signed webhooks, /.well-known/acp.json discovery, AR-fiscal compliance (auto-issued AFIP/ARCA factura). Infrastructure package — no LLM tool surface.",
    "tools": []
  },
  {
    "package": "@ar-agents/anses",
    "version": "0.1.0",
    "tools": [
      {
        "name": "anses_get_cuil_status",
        "description": "Look up a CUIL's ANSES status (consultar situación en ANSES), activo / jubilado / pensionado / desempleado_con_subsidio / desempleado_sin_subsidio / inactivo / fallecido. Returns last-reported employe",
        "input": {
          "cuil": "11-digit CUIL"
        },
        "returns": "CuilStatusResult",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      },
      {
        "name": "anses_get_family_allowances",
        "description": "List family-allowance entitlements ANSES has on file for a CUIL (asignaciones familiares): AUH (per-child), AUE (pregnancy), SUAF (formal workers), Pensión No Contributiva, Tarjeta Alimentar. Each ent",
        "input": {
          "cuil": "11-digit CUIL"
        },
        "returns": "FamilyAllowanceEntitlement[]",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      },
      {
        "name": "anses_get_minimo_jubilatorio",
        "description": "Look up the haber mínimo jubilatorio (minimum monthly pension) for a given period, returned in ARS centavos. Use to compare against an actual jubilación amount or to populate compliance UIs.",
        "input": {
          "period": "YYYY-MM"
        },
        "returns": "MinimoJubilatorioRecord | null",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/ap2",
    "version": "0.2.0",
    "description": "Google AP2 (Agent Payments Protocol) primitives — Mandate verification + signing (ES256 / JWS), canonical claims, multi-hop mandate chains, budget tracker. Infrastructure package — no LLM tool surface.",
    "tools": []
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/banking",
    "version": "0.5.0",
    "description": "Argentine banking primitives (CBU/CVU + bank lookup) and BCRA Central de Deudores adapter as drop-in tools for the Vercel AI SDK.",
    "tools": [
      {
        "name": "get_bcra_variable",
        "description": "Fetch the historical series of a BCRA indicator (serie histórica de una variable del BCRA) by id. USE THIS WHEN: the user wants historical values of a specific variable (cotización USD, CER, UVA, infl"
      },
      {
        "name": "get_cer",
        "description": "Get the current CER coefficient (coeficiente CER hoy, ajuste por inflación; BCRA variable id 30). CER is the official inflation-tracking coefficient used to adjust regulated debt and contracts. USE TH"
      },
      {
        "name": "get_reservas_bcra",
        "description": "Get BCRA international reserves (reservas del BCRA, Reservas Internacionales; variable id 1). USE THIS WHEN: the user asks about reservas, USD reserves, or BCRA balance sheet. Returns the latest value"
      },
      {
        "name": "get_usd_oficial",
        "description": "Get the official USD exchange rate (dólar oficial, a cuánto está el dólar, cotización USD; Tipo de Cambio Minorista, BCRA variable id 4). Returns the current value + date + the most recent N daily dat"
      },
      {
        "name": "get_uva",
        "description": "Get the current UVA value (valor UVA hoy; Unidad de Valor Adquisitivo, BCRA variable id 31). UVA is the inflation-adjusted unit used for AR mortgages, fixed-term deposits, and rentals. USE THIS WHEN: "
      },
      {
        "name": "list_banks",
        "description": "List Argentine banks (listar bancos argentinos) with their BCRA codes. USE THIS WHEN: you need to render a dropdown of banks for the user to pick from, or need to enumerate available entities for a wo",
        "input": {},
        "output": "{ banks: BankInfo[] }"
      },
      {
        "name": "list_bcra_variables",
        "description": "List BCRA monetary indicators (principales variables del BCRA) with their current latest value and ID. Returns variables like Reservas Internacionales, Tipo de Cambio Minorista USD, Tipo de Cambio May"
      },
      {
        "name": "list_psps",
        "description": "List Argentine fintech wallets / PSPs (listar billeteras virtuales, Mercado Pago, Ualá, Naranja X, Personal Pay, etc.) with their CVU prefixes. USE THIS WHEN: you need to render a dropdown of fintech ",
        "input": {},
        "output": "{ psps: BankInfo[] }"
      },
      {
        "name": "lookup_bank_by_code",
        "description": "Identify the Argentine bank or PSP behind an entity code (de qué banco es este CBU, código de entidad BCRA). PURE FUNCTION: in-memory lookup, free, sub-millisecond. Returns the entity's full legal nam",
        "input": {
          "code": "string"
        },
        "output": "{ code, found, entity }"
      },
      {
        "name": "lookup_credit_situation",
        "description": "Check a CUIT's credit standing in the BCRA Central de Deudores (consultar deudores BCRA, situación crediticia). Returns the worst situation code (1=normal, 2=low risk <90 days, 3=medium risk 90-180 da",
        "input": {
          "cuit": "string"
        },
        "output": "BcraDeudaResult & { worstSituationDescription }"
      },
      {
        "name": "validate_cbu",
        "description": "Validate an Argentine CBU or CVU bank account number (validar CBU, validar CVU). CBU = Clave Bancaria Uniforme (traditional bank account), CVU = Clave Virtual Uniforme (fintech wallet account), checke",
        "input": {
          "cbu": "string"
        },
        "output": "CbuParseResult"
      }
    ],
    "name": "@ar-agents/banking",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 11
    }
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/banking-bcra",
    "version": "0.1.0",
    "tools": [
      {
        "name": "bcra_get_debt",
        "description": "Raw current debt status from the BCRA Central de Deudores (consultar deudas en el BCRA): one row per entidad reporting, with situación 1-6, monto, judicial/fraude/refinanciación flags. Returns BcraNot",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bcra_get_debt_summary",
        "description": "One-shot credit check for a CUIT (consultar deudores BCRA, riesgo crediticio): total reported debt (centavos), worst situación across entidades, judicial/fraude/refinanciación flags, plus a risk band ",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bcra_get_historical_debt",
        "description": "24-month debt history for a CUIT (historial de deudas BCRA). Use for trend analysis ('has this taxpayer been deteriorating?') or to confirm a one-off vs a chronic pattern.",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bcra_get_bounced_checks",
        "description": "Bounced-check history for a CUIT (cheques rechazados) (causa de rechazo + monto + fecha + whether subsequently paid). Independent of the Central de Deudores debt status, a clean debt record + bounced ",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/bind",
    "version": "0.1.0",
    "tools": [
      {
        "name": "bind_list_accounts",
        "description": "List the BIND bank accounts visible to the configured credentials, with balances and CBUs.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bind_get_movements",
        "description": "Get the movements (transactions) of a BIND bank account with date filters and pagination.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bind_get_cbu_owner",
        "description": "Check who owns a CBU, CVU, or alias before paying.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bind_create_transfer",
        "description": "Transfer pesos from a BIND bank account to a CBU, CVU, or alias. Irreversible once completed.",
        "sideEffects": "irreversible",
        "idempotent": true,
        "requiresConfirmation": true
      },
      {
        "name": "bind_create_debin",
        "description": "Create a DEBIN request to collect pesos from a buyer's account; the buyer approves it on their side.",
        "sideEffects": "creates resource",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "bind_get_echeqs",
        "description": "List echeqs (electronic checks) for a BIND account filtered by status and perspective.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/boletin-oficial",
    "version": "0.1.0",
    "description": "Boletín Oficial de la República Argentina — search published normas, fetch by ID, query the day's edition, subscribe to keyword/CUIT/organismo updates.",
    "tools": [
      {
        "name": "bo_search",
        "description": "Search the Argentine Boletín Oficial (buscar en el Boletín Oficial). Returns a list of normas (laws, decrees, resoluciones, sociedades, contracting, judicial notices) matching free-text query + option"
      },
      {
        "name": "bo_get_norma",
        "description": "Fetch a single norma from the Boletín Oficial by id (consultar una norma). Returns the title, organismo, full text, fecha de publicación, and any CUITs mentioned. USE THIS WHEN: you have an id (from `"
      },
      {
        "name": "bo_today",
        "description": "Fetch today's Boletín Oficial publications (qué salió hoy en el Boletín Oficial), optionally filtered by sección. USE THIS WHEN: the user wants a daily summary of newly-published norms, e.g. `qué publ"
      },
      {
        "name": "bo_subscribe",
        "description": "Subscribe to Boletín Oficial alerts (suscribirse a alertas del Boletín Oficial). The matcher fires whenever a new norma matches the criteria, keyword, CUIT, organismo, sección, or tipo. USE THIS WHEN:"
      },
      {
        "name": "bo_list_subscriptions",
        "description": "List active Boletín Oficial subscriptions (listar suscripciones). USE THIS WHEN: the user wants to see what they've subscribed to. Pass `owner_id` to scope to a specific user/tenant."
      },
      {
        "name": "bo_unsubscribe",
        "description": "Remove a Boletín Oficial subscription by id (cancelar una suscripción). USE THIS WHEN: the user wants to stop a previous bo_subscribe."
      }
    ]
  },
  {
    "package": "@ar-agents/cnv-emisor",
    "version": "0.1.0",
    "tools": [
      {
        "name": "cnv_get_issuer",
        "description": "Look up a CNV-registered securities issuer (consultar emisora CNV) by their stable code (e.g. 'YPF', 'GGAL', 'TXAR'). Returns denominación, CUIT, categoría, sector classification, and active status. R",
        "input": {
          "code": "issuer code, e.g. YPF"
        },
        "returns": "IssuerRecord | null",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      },
      {
        "name": "cnv_list_hechos_relevantes",
        "description": "List 'hechos relevantes' (material facts) filed by an issuer in the CNV AIF. Filter by category (asamblea / dividendo / estado_financiero / oferta_publica / cambio_control / garantia / otro) and/or si",
        "input": {
          "issuerCode": "string",
          "sinceIso": "ISO 8601 optional",
          "category": "optional enum",
          "limit": "1-100"
        },
        "returns": "HechoRelevante[]",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      },
      {
        "name": "cnv_list_financial_statements",
        "description": "List financial statements filed with CNV (estados financieros presentados en CNV): annual / quarterly / intermediate, in the AIF. Each entry carries the period end, submitted timestamp, kind, and AIF ",
        "input": {
          "issuerCode": "string",
          "limit": "1-100"
        },
        "returns": "FinancialStatementRecord[]",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/constancia",
    "version": "0.1.0",
    "description": "ARCA Constancia de Inscripción — official fiscal document (régimen, monotributo categoría, impuestos, domicilio, actividades) plus the PDF artifact. Browser-backed: drives the public web form (no Clave Fiscal) via the companion afip-constancia skill on browserbase/skills.",
    "tools": [
      {
        "name": "constancia_inscripcion",
        "description": "Get the official AFIP/ARCA registration certificate for a CUIT (constancia de inscripción, obtené la Constancia de Inscripción de ARCA, ex-AFIP): el régimen (monotributo + categoría / responsable insc"
      }
    ]
  },
  {
    "package": "@ar-agents/dnrpa",
    "version": "0.1.0",
    "tools": [
      {
        "name": "dnrpa_lookup_dominio",
        "description": "Look up an Argentine vehicle plate (dominio/patente) against DNRPA. Accepts both new Mercosur format (LL000LL like 'AB123CD') and the old Argentine format (LLL000 like 'FFF123'). Returns marca/modelo/",
        "input": {
          "dominio": "LL000LL or LLL000 plate"
        },
        "returns": "DominioLookupResult",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/facturacion",
    "version": "0.4.0",
    "description": "AFIP/ARCA factura electrónica (WSFE) as drop-in tools for the Vercel AI SDK. Reuses WSAA from @ar-agents/identity.",
    "tools": [
      {
        "name": "consultar_factura_emitida",
        "description": "Look up an already-issued invoice (consultar factura emitida, verificar un CAE propio): CAE, fecha, importes, doc receptor. USE WHEN: necesitás verificar que un CAE es válido y matchea con tu base de ",
        "input": {
          "ptoVta": "number?",
          "cbteTipo": "number",
          "cbteNro": "number"
        },
        "output": "ConsultarComprobanteResult"
      },
      {
        "name": "consultar_ultimo_comprobante",
        "description": "Get the last authorized invoice number (consultar último comprobante autorizado) para un (PtoVta, CbteTipo), i.e. cuál fue el número del último Factura C emitido desde el punto de venta 1. USE BEFORE ",
        "input": {
          "ptoVta": "number?",
          "cbteTipo": "number"
        },
        "output": "{ ptoVta, cbteTipo, cbteNro, proximoNumero, tipoComprobanteDescripcion }"
      },
      {
        "name": "emitir_factura",
        "description": "Issue an electronic invoice and get its CAE (emitir factura electrónica, facturar) via AFIP/ARCA WSFE. Solicita el CAE (Código de Autorización Electrónico) que valida la factura ante AFIP. RETURNS: el",
        "input": "SolicitarCaeInput",
        "output": "SolicitarCaeResult & { ok, tipoComprobanteDescripcion }"
      },
      {
        "name": "health_check_afip",
        "description": "Health check de AFIP WSFE, devuelve el status de los servidores app, db, y auth. Use as a /health endpoint o como pre-flight rápido antes de emitir muchas facturas. PURE READ, latencia < 200ms.",
        "input": {},
        "output": "DummyResult & { ok }"
      },
      {
        "name": "obtener_alicuotas_iva",
        "description": "List VAT rates (alícuotas de IVA) según AFIP (21%=5, 10.5%=4, 27%=6, 0%=3, etc.). USE WHEN: el usuario necesita ver las opciones para construir una factura B o A. HEAVY: round-trip a AFIP. Preferí `Al",
        "input": {},
        "output": "{ items: CatalogItem[] }"
      },
      {
        "name": "obtener_cotizacion",
        "description": "Get the official AFIP exchange rate (cotización oficial de moneda extranjera vs ARS). REQUIRED antes de emitir cualquier factura no-PES (AFIP rechaza si la cotización está desactualizada). Devuelve el",
        "input": {
          "monId": "string"
        },
        "output": "{ monId, cotiz, fchCotiz }"
      },
      {
        "name": "obtener_tipos_comprobante",
        "description": "List AFIP voucher types (tipos de comprobante) (Factura A=1, B=6, C=11, Nota Crédito A=3, etc.). USE WHEN: necesitás mostrar al usuario la lista actualizada (puede haber tipos nuevos que no están en l",
        "input": {},
        "output": "{ items: CatalogItem[] }"
      },
      {
        "name": "obtener_tipos_concepto",
        "description": "List concept types (tipos de concepto): Productos (1), Servicios (2), Productos y Servicios (3). HEAVY: round-trip a AFIP. Preferí `Concepto` constants.",
        "input": {},
        "output": "{ items: CatalogItem[] }"
      },
      {
        "name": "obtener_tipos_documento",
        "description": "List AFIP document types (tipos de documento) (CUIT=80, DNI=96, Pasaporte=94, Consumidor Final=99, etc.). HEAVY: round-trip a AFIP. Preferí los constants de `DocTipo` para flujos comunes.",
        "input": {},
        "output": "{ items: CatalogItem[] }"
      },
      {
        "name": "obtener_tipos_moneda",
        "description": "List currencies accepted for invoicing (tipos de moneda) (PES = Pesos, DOL = Dólar, 060 = Euro, 012 = Real, etc.). USE WHEN: el usuario quiere emitir Factura E (exportación) o multi-moneda. HEAVY: rou",
        "input": {},
        "output": "{ items: CatalogItem[] }"
      }
    ],
    "name": "@ar-agents/facturacion",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 10
    }
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/fecred",
    "version": "0.1.0",
    "tools": [
      {
        "name": "fecred_check_obligation",
        "description": "Check if an invoice to a given CUIT must be a Factura de Credito Electronica MiPyME (FCE). Returns obligado plus montoDesde, the live regime threshold from AFIP.",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "fecred_list_received",
        "description": "List FCEs received (or emitted) by the represented CUIT, with state filters. estadoCmp='Recepcionado' lists FCEs awaiting acceptance or rejection.",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "fecred_accept_invoice",
        "description": "Accept a received electronic credit invoice (FCE) and its cuenta corriente balance. Irreversible legal act: the FCE becomes a negotiable credit title.",
        "sideEffects": "network write",
        "idempotent": false,
        "requiresConfirmation": true
      },
      {
        "name": "fecred_reject_invoice",
        "description": "Reject a received electronic credit invoice (FCE) with at least one justified motivo de rechazo. Irreversible legal act, only valid inside the legal acceptance window.",
        "sideEffects": "network write",
        "idempotent": false,
        "requiresConfirmation": true
      },
      {
        "name": "fecred_health",
        "description": "Ping the AFIP WSFECred service (dummy operation). Returns appServer/dbServer/authServer statuses.",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/firma-digital",
    "version": "0.1.0",
    "description": "AR digital signature primitives — PKCS#7/CMS verification with AC-Raíz/ONTI trust-anchor heuristic and certificate fingerprint pinning.",
    "tools": [
      {
        "name": "firma_inspect_cert",
        "description": "Inspect an Argentine Firma Digital X.509 certificate (inspeccionar certificado de firma digital, PEM-encoded) and return its subject, issuer, validity window, CUIT (when embedded), public-key info, an"
      },
      {
        "name": "firma_verify_chain",
        "description": "Verify an X.509 certificate chain (verificar cadena de certificados; PEM bundle, leaf → root), checks issuer-by-subject linking, RSA signatures, validity window. Returns valid/reason + per-cert trace."
      },
      {
        "name": "firma_is_onti_issued",
        "description": "Check if a cert was issued under Argentine Firma Digital (¿es un certificado de firma digital argentina? AC-Raíz / ONTI ecosystem); quick yes/no. Heuristic-based on issuer DN attributes. PURE FUNCTION"
      },
      {
        "name": "firma_verify_cms_signature",
        "description": "Verify a digitally signed document (verificar firma digital de un documento): detached PKCS#7 / CMS signature against a payload (e.g., `firma.p7s` produced by an AR signing tool). Returns valid/reason"
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/gde-tad",
    "version": "0.3.0",
    "description": "TAD (Trámites a Distancia) + GDE (Gestión Documental Electrónica) primitives — DEC inbox polling, Mis Trámites listing, IGJ inscription pre-flight. The 4th pieza for sociedades-IA.",
    "tools": [
      {
        "name": "get_critical_notifications",
        "description": "List only critical DEC notifications (notificaciones críticas del DEC), ordenadas por fecha de respuesta más cercana. Use this in the agent's morning loop to know what MUST be answered today/this week"
      },
      {
        "name": "list_domicilio_inbox",
        "description": "List electronic-domicile notifications (notificaciones del Domicilio Electrónico Constituido, DEC) de una sociedad/persona. Cada notificación incluye organismo, asunto, fecha de notificación, fecha de"
      },
      {
        "name": "list_mis_tramites",
        "description": "List TAD case files where the company/person is a party (expedientes y trámites en TAD). Útil para reporting, due diligence, y para el agente saber qué tiene en curso vs. qué resolvió. Read-only, no i"
      },
      {
        "name": "validate_igj_inscription",
        "description": "Pre-flight validator para una inscripción IGJ (SAS/SRL/SA/SOCIEDAD-IA). Catches the ~30% of rejections that are mechanical (denominación reservada, capital bajo el mínimo, aportes que no suman, CUIT i"
      }
    ],
    "name": "@ar-agents/gde-tad",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 4
    }
  },
  {
    "$schema": "https://github.com/ar-agents/ar-agents/blob/main/tools-manifest.schema.json",
    "package": "@ar-agents/identity",
    "version": "0.8.0",
    "factory": "identityTools",
    "tools": [
      {
        "name": "lookup_cuit_afip",
        "description": "Look up a CUIT/CUIL in the AFIP/ARCA taxpayer registry (consultar CUIT en AFIP, datos del contribuyente, padrón). Returns taxpayer name, tax condition (Monotributo / Responsable Inscripto / etc.), mon",
        "input": {
          "cuit": {
            "type": "string",
            "required": true,
            "description": "The CUIT/CUIL to look up. Pass the validated/normalized form (output of validate_cuit.normalized)."
          }
        },
        "output": {
          "cuit": "string",
          "available": "boolean",
          "error": "string | null (when available is false, contains setup steps; surface verbatim)",
          "data": {
            "nombre": "string",
            "condicion": "MONOTRIBUTO | RESPONSABLE INSCRIPTO | EXENTO | ...",
            "monotributoCategoria": "A-K | null",
            "fechaInscripcion": "ISO date | null",
            "domicilioFiscal": "string | null",
            "actividades": "string[]"
          }
        }
      },
      {
        "name": "validate_cuit",
        "description": "Validate a CUIT/CUIL Argentine tax ID (validar CUIT, verificar CUIT/CUIL) via the AFIP modulo-11 check digit algorithm. PURE FUNCTION: no API call, no environment dependencies, sub-millisecond latency",
        "input": {
          "cuit": {
            "type": "string",
            "required": true,
            "description": "The CUIT/CUIL to validate. Accepts any format with or without separators (20-X-Y, 20.X.Y, 20 X Y, 20XY)."
          }
        },
        "output": {
          "valid": "boolean",
          "normalized": "string (11 digits)",
          "formatted": "string | null (XX-XXXXXXXX-X)",
          "prefix": "string | null",
          "body": "string | null",
          "checkDigit": "string | null",
          "personType": "fisica_masculina | fisica_femenina | fisica_extranjera | juridica | juridica_alternativa | desconocida",
          "personTypeDescription": "string (Spanish description)",
          "error": "string | null (Spanish actionable error message; surface verbatim to users)"
        }
      }
    ],
    "name": "@ar-agents/identity",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 2
    }
  },
  {
    "$schema": "https://github.com/ar-agents/ar-agents/blob/main/tools-manifest.schema.json",
    "package": "@ar-agents/identity-attest",
    "version": "0.5.0",
    "factory": "identityAttestTools",
    "tools": [
      {
        "name": "check_verification_status",
        "description": "Check verification status (estado de la verificación): pending, completed, expired, or failed. Use this between user turns when waiting for the user to click a magic link.",
        "input": {
          "request_id": "string"
        },
        "output": {
          "request_id": "string",
          "status": "pending | verified | failed | expired | cancelled",
          "method": "string",
          "subject": "{type, value}",
          "trust_level": "number",
          "expires_at": "ISO date",
          "attestation": "object | null (set when status=verified)"
        }
      },
      {
        "name": "get_attestation",
        "description": "Fetch the signed attestation for a completed verification (obtener la atestación firmada). Returns null if not yet verified. The attestation includes trust_level (0-1), method, subject, claims, and a ",
        "input": {
          "request_id": "string"
        },
        "output": "Full Attestation object (with signature) or {found: false}"
      },
      {
        "name": "list_verification_methods",
        "description": "List available verification methods (métodos de verificación disponibles) the host app has registered (with trust levels). Use to know what options are available before calling request_identity_verifi",
        "input": {},
        "output": {
          "count": "number",
          "methods": "array of {id, trust_level, description}"
        }
      },
      {
        "name": "request_identity_verification",
        "description": "Start an identity verification flow (verificar identidad, enviar código de verificación) to prove the user controls a phone, email, or other identity asset. Returns a request_id you'll use to check st",
        "input": {
          "method": "string (e.g. whatsapp_otp, email_magic_link)",
          "subject_type": "phone | email | oauth | dni | cuit | custom",
          "subject_value": "string",
          "external_reference": "string?"
        },
        "output": {
          "request_id": "uuid",
          "method": "string",
          "trust_level": "number 0..1",
          "status": "pending",
          "expires_at": "ISO date (default 15min from now)",
          "verification_url": "URL | null (only for magic-link adapters)",
          "next_step": "string (instructions to surface to the user verbatim)"
        }
      },
      {
        "name": "submit_otp_code",
        "description": "Submit the OTP verification code (ingresar código de verificación) the user dictated back to you (after they received it via WhatsApp/SMS/Email). Returns the signed attestation if correct, throws Inva",
        "input": {
          "request_id": "string",
          "code": "string (extract just the digits)"
        },
        "output": {
          "verified": "true",
          "request_id": "string",
          "trust_level": "number",
          "subject": "{type, value}",
          "verified_at": "ISO date",
          "expires_at": "ISO date",
          "message": "string"
        }
      }
    ],
    "name": "@ar-agents/identity-attest",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 5
    }
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/igj",
    "version": "0.1.0",
    "description": "Inspección General de Justicia (IGJ) public registry primitives — search corporate entities, fetch domicilios, autoridades, balances, asambleas via the open data CKAN at datos.jus.gob.ar.",
    "tools": [
      {
        "name": "igj_search_entities",
        "description": "Search IGJ-registered Argentine entities (buscar sociedades en IGJ; sociedades, asociaciones, fundaciones) via the public CKAN open data at datos.jus.gob.ar. Returns matching entities + a `coverageNot"
      },
      {
        "name": "igj_get_entity",
        "description": "Fetch a single IGJ entity by its dataset id (consultar una entidad IGJ). Returns the entity record including razón social, CUIT (when present), tipo de entidad, fecha de inscripción, matrícula. Return"
      },
      {
        "name": "igj_get_domicilios",
        "description": "Fetch the registered domicilios (addresses) for an IGJ entity by its id. Multiple domicilios may exist (legal, fiscal, real). USE THIS WHEN: the user wants the registered address of a sociedad/asociac"
      },
      {
        "name": "igj_get_autoridades",
        "description": "Fetch the registered authorities (directors, officers, trustees) of an IGJ entity. Includes nombre, cargo, fecha de designación, and inferred genre when available. USE THIS WHEN: the user asks who is "
      },
      {
        "name": "igj_get_balances",
        "description": "Fetch the balances (financial reports) filed at IGJ for an entity. Includes cierre de ejercicio, número de ejercicio, fecha de presentación. USE THIS WHEN: the user wants to know if a sociedad is up t"
      },
      {
        "name": "igj_get_asambleas",
        "description": "Fetch the registered asambleas (meetings) of an IGJ entity. Includes tipo (ordinaria/extraordinaria) and fecha. USE THIS WHEN: you want to know when a sociedad held its last asamblea or track the cale"
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/iibb",
    "version": "0.2.0",
    "tools": [
      {
        "name": "iibb_calculate_retention",
        "description": "Calculate the IIBB gross-receipts retention (calcular retención de Ingresos Brutos) on a base imponible in a given jurisdiction. Pure math: amount = base × rate (fraction), unless base < minimumThresh",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iibb_calculate_perception",
        "description": "Calculate the IIBB perception (calcular percepción de Ingresos Brutos) on a base imponible in a given jurisdiction. Symmetrical to retention in v0.1; some jurisdictions add a fixed component which wil",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iibb_compute_ddjj",
        "description": "Assemble a monthly IIBB tax return (armar la DDJJ mensual de Ingresos Brutos) from raw income lines + a rate-book. Supports the LOCAL regime (single jurisdiction) and the CM general regime (Article 2,",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iibb_lookup_padron",
        "description": "Look up a CUIT in a jurisdiction's IIBB registry (consultar padrón de Ingresos Brutos). Returns null if not registered. Throws IibbUnconfiguredError if the adapter for that jurisdiction is not wired (",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "package": "@ar-agents/inpi",
    "version": "0.1.0",
    "tools": [
      {
        "name": "inpi_search_trademark",
        "description": "Search INPI trademarks by name (buscar marcas registradas en INPI), case-insensitive substring. Returns the matching registrations with their Nice class, status (presentada/publicada/oposicion/concedi",
        "input": {
          "q": "substring (min 2 chars)",
          "niceClass": "optional 1-45",
          "status": "optional enum",
          "limit": "1-100"
        },
        "returns": "SearchResult",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      },
      {
        "name": "inpi_get_trademark",
        "description": "Look up an INPI trademark by registration number (consultar una marca por acta) (registration number, e.g. '3792456'). Returns the full record or null if not found.",
        "input": {
          "acta": "string"
        },
        "returns": "TrademarkRecord | null",
        "sideEffect": "none (read-only)",
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/iva-percepciones",
    "version": "0.1.0",
    "tools": [
      {
        "name": "iva_perception_calculate",
        "description": "Compute the VAT perception for a sale invoice (calcular percepción de IVA, the extra charge added on top of IVA). Returns 0 with a `waiverReason` when the buyer is exento / monotributista / consumidor",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iva_perception_build_ddjj",
        "description": "Assemble the monthly SIRE perception return (armar DDJJ SIRE de percepciones de IVA) with per-regime and per-buyer breakdowns. Pure aggregation.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iva_perception_submit_ddjj",
        "description": "Submit an assembled SIRE perception return (presentar DDJJ de percepciones de IVA). Throws unless the host wired a real adapter. Files a tax return, confirmation gate required.",
        "sideEffects": "files tax return",
        "idempotent": true,
        "requiresConfirmation": true
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/iva-retenciones",
    "version": "0.1.0",
    "tools": [
      {
        "name": "iva_retention_calculate",
        "description": "Compute the VAT retention on a supplier payment (calcular retención de IVA) per RG 2854/10. Returns 0 with `waiverReason` when the supplier is exento / monotributista, when the IVA component is below ",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iva_retention_build_ddjj",
        "description": "Assemble the monthly SIRE retention return (armar DDJJ SIRE de retenciones de IVA) with per-regime and per-supplier breakdowns. Pure aggregation.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "iva_retention_submit_ddjj",
        "description": "Submit an assembled SIRE retention return to AFIP/ARCA (presentar DDJJ de retenciones de IVA). Throws unless the host wired a real adapter. Files a tax return, confirmation gate required.",
        "sideEffects": "files tax return",
        "idempotent": true,
        "requiresConfirmation": true
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/mcp",
    "version": "0.9.0",
    "description": "MCP (Model Context Protocol) server bundling the @ar-agents/* toolkit (12 subpackages, 133 tools) for any MCP host (Claude Desktop, Cursor, Continue, Cline). Infrastructure package — exposes the underlying tool surface via stdio transport.",
    "tools": []
  },
  {
    "$schema": "https://ar-agents.ar/schema/tools-manifest.json",
    "package": "@ar-agents/mercadolibre",
    "version": "0.1.0",
    "description": "Mercado Libre Agent Toolkit for the Vercel AI SDK 6.",
    "site_ids": [
      "MLA",
      "MLB",
      "MLM",
      "MLC",
      "MCO",
      "MPE",
      "MLU"
    ],
    "tools": [
      {
        "name": "list_my_items",
        "summary": "List the configured seller's listings (active, paused, or closed).",
        "input": {
          "status": {
            "type": "enum",
            "values": [
              "active",
              "paused",
              "closed",
              "all"
            ],
            "optional": true
          },
          "search": {
            "type": "string",
            "optional": true,
            "description": "Free-text filter applied to title."
          },
          "limit": {
            "type": "number",
            "optional": true,
            "default": 50,
            "max": 100
          }
        },
        "output": {
          "items": {
            "type": "array",
            "of": "ItemSummary"
          },
          "total": {
            "type": "number"
          }
        },
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "get_item",
        "summary": "Fetch a single listing by id.",
        "input": {
          "itemId": {
            "type": "string",
            "description": "Site-prefixed item id, e.g. MLA1402155766."
          }
        },
        "output": "Item",
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "create_item",
        "summary": "Create a new listing.",
        "input": "ItemCreateRequest",
        "output": {
          "id": "string",
          "status": "string",
          "permalink": "string"
        },
        "side_effects": "creates a real listing on MELI",
        "rate_limit_class": "write",
        "preconditions": [
          "category_id must exist for the configured site",
          "listing_type_id must be valid for the seller's reputation level"
        ]
      },
      {
        "name": "update_item_price_or_stock",
        "summary": "Update price and/or available_quantity on an existing listing.",
        "input": {
          "itemId": "string",
          "price": {
            "type": "number",
            "optional": true
          },
          "available_quantity": {
            "type": "number",
            "optional": true
          }
        },
        "output": "ItemSummary",
        "side_effects": "modifies the listing",
        "rate_limit_class": "write",
        "idempotent": true,
        "notes": "available_quantity = 0 auto-pauses the listing."
      },
      {
        "name": "categorize_listing_and_plan_attributes",
        "summary": "Predict the category for a free-text title and return the required attributes.",
        "input": {
          "title": "string",
          "siteId": {
            "type": "string",
            "optional": true,
            "description": "Defaults to the toolkit's configured site."
          }
        },
        "output": {
          "predicted": {
            "category_id": "string",
            "name": "string",
            "path": "array<string>"
          },
          "requiredAttributeIds": "array<string>",
          "technicalSpecs": "TechnicalSpecResponse"
        },
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "list_unanswered_questions",
        "summary": "List questions on the seller's listings that haven't been answered.",
        "input": {
          "itemId": {
            "type": "string",
            "optional": true
          },
          "limit": {
            "type": "number",
            "optional": true,
            "default": 50
          }
        },
        "output": {
          "questions": "array<Question>",
          "total": "number"
        },
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "answer_question",
        "summary": "Post an answer to a question.",
        "input": {
          "questionId": "number",
          "text": {
            "type": "string",
            "max_length": 2000
          }
        },
        "output": {
          "id": "number",
          "text": "string",
          "status": "string"
        },
        "side_effects": "writes a public answer visible on the listing",
        "rate_limit_class": "write"
      },
      {
        "name": "classify_question_spam",
        "summary": "Heuristic spam classifier — labels a question as spam, borderline, or ham.",
        "input": {
          "questionText": "string",
          "askerProfile": {
            "account_age_days": {
              "type": "number",
              "optional": true
            },
            "answered_questions": {
              "type": "number",
              "optional": true
            }
          },
          "recentQuestionsByThisAsker": {
            "type": "array<string>",
            "optional": true
          }
        },
        "output": {
          "label": {
            "type": "enum",
            "values": [
              "spam",
              "borderline",
              "ham"
            ]
          },
          "score": {
            "type": "number",
            "range": "0..1"
          },
          "features": "QuestionSpamFeatures"
        },
        "side_effects": "none — pure local function, no MELI call",
        "rate_limit_class": "none"
      },
      {
        "name": "list_recent_orders",
        "summary": "List the seller's recent orders.",
        "input": {
          "status": {
            "type": "enum",
            "values": [
              "paid",
              "confirmed",
              "cancelled",
              "invalid",
              "all"
            ],
            "optional": true
          },
          "dateFrom": {
            "type": "ISO8601",
            "optional": true
          },
          "dateTo": {
            "type": "ISO8601",
            "optional": true
          },
          "limit": {
            "type": "number",
            "optional": true,
            "default": 50
          }
        },
        "output": {
          "orders": "array<OrderSummary>",
          "total": "number"
        },
        "side_effects": "none",
        "rate_limit_class": "read",
        "defaults": "if no status, returns paid + confirmed; if no dateFrom, returns last 24h"
      },
      {
        "name": "get_order",
        "summary": "Fetch a single order with full detail (items, payments, buyer billing).",
        "input": {
          "orderId": "number"
        },
        "output": "Order",
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "list_open_claims",
        "summary": "List open claims/disputes/mediations for the seller, sorted by due_date ASC.",
        "input": {
          "stage": {
            "type": "enum",
            "values": [
              "claim",
              "dispute",
              "mediation"
            ],
            "optional": true
          },
          "limit": {
            "type": "number",
            "optional": true,
            "default": 50
          }
        },
        "output": {
          "claims": "array<Claim>",
          "total": "number"
        },
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "defend_claim",
        "summary": "Defend a claim — uploads N evidences in parallel + optional message.",
        "input": {
          "claimId": "number",
          "evidences": "array<{ evidence_type, text?, file_id? }>",
          "message": {
            "type": "string",
            "optional": true
          }
        },
        "output": {
          "claim": "Claim",
          "uploadedEvidences": "array<{ type: EvidenceType }>",
          "messagePosted": "{ message: string } | null"
        },
        "side_effects": "uploads evidences + posts a message visible to the buyer + MELI mediator",
        "rate_limit_class": "write"
      },
      {
        "name": "get_seller_reputation",
        "summary": "Read the seller's reputation (thermometer + metrics + pre-evaluated alerts).",
        "input": {
          "sellerId": {
            "type": "number",
            "optional": true
          }
        },
        "output": {
          "level_id": {
            "type": "enum",
            "values": [
              "5_green",
              "4_light_green",
              "3_yellow",
              "2_orange",
              "1_red"
            ]
          },
          "metrics": "SellerReputationMetrics",
          "alerts": "array<ReputationAlert>"
        },
        "side_effects": "none",
        "rate_limit_class": "read"
      },
      {
        "name": "list_promotion_candidates",
        "summary": "List items eligible for current MELI promotions (discount % suggested by MELI).",
        "input": {
          "sellerId": {
            "type": "number",
            "optional": true
          }
        },
        "output": {
          "candidates": "array<PromotionCandidate>"
        },
        "side_effects": "none",
        "rate_limit_class": "read"
      }
    ]
  },
  {
    "$schema": "https://github.com/ar-agents/ar-agents/blob/main/tools-manifest.schema.json",
    "package": "@ar-agents/mercadopago",
    "version": "0.18.0",
    "factory": "mercadoPagoTools",
    "tools": [
      {
        "name": "analyze_payment_3ds",
        "description": "Pure local analyzer for a Payment's 3DS (Strong Customer Authentication) state. Pass a payment_id (string) and the tool fetches the Payment then derives { status: 'not_required'|'frictionless'|'challe"
      },
      {
        "name": "calculate_installments",
        "description": "Calculate installment options for an amount (calcular cuotas, cuotas sin interés). THE killer Argentine feature, returns options like '12 cuotas sin interés de $X' (recommended_message field) which yo",
        "input": {
          "amount_ars": "number positive",
          "payment_method_id": "string? (e.g. visa, master, naranja)",
          "bin": "string? 6-8 chars (first digits of card for issuer-specific promos)"
        },
        "output": {
          "amount": "number",
          "offers": "array of {payment_method_id, payment_type_id, issuer_name, options: [{installments, installment_amount, total_amount, installment_rate, recommended_message}]}"
        }
      },
      {
        "name": "cancel_order",
        "description": "Cancel an Order. Releases any auth-holds and marks the Order as canceled. For orders that have already been CAPTURED, use refund_payment instead, cancel only works pre-capture. **IRREVERSIBLE, confirm",
        "input": {
          "order_id": "string"
        },
        "output": {
          "order_id": "string",
          "status": "string"
        }
      },
      {
        "name": "cancel_payment",
        "description": "Cancel a pending or in_process Mercado Pago payment (cancelar un pago pendiente); only works before approval. Once approved, use refund_payment instead. Common use: cancel an unpaid ticket payment tha",
        "input": {
          "payment_id": "string"
        },
        "output": {
          "payment_id": "string",
          "status": "cancelled",
          "message": "string"
        }
      },
      {
        "name": "cancel_point_payment_intent",
        "description": "Cancel an OPEN point payment intent before the buyer interacts with the device. ONLY WORKS while state='OPEN', once the buyer taps, you can't cancel; refund_payment after the fact instead. **IRREVERSI"
      },
      {
        "name": "cancel_qr_payment",
        "description": "Cancel a pending QR order on a POS (cancelar un QR pendiente). Necessary if the buyer never scans, otherwise the next create_qr_payment on the same POS returns 409. **IRREVERSIBLE, but low-stakes sinc"
      },
      {
        "name": "cancel_subscription",
        "description": "Cancel an active Mercado Pago subscription (cancelar suscripción, dar de baja). After cancellation, MP will not charge the customer again. This action is irreversible, confirm with the user before cal",
        "input": {
          "subscription_id": "string"
        },
        "output": {
          "subscription_id": "string",
          "status": "cancelled",
          "message": "string"
        }
      },
      {
        "name": "capture_order",
        "description": "Capture a previously-authorized Order (only for orders created with capture_mode='manual'). Captures up to the originally-authorized amount; pass amount for partial capture. Common use: ride-share mar",
        "input": {
          "order_id": "string",
          "amount": "number?"
        },
        "output": {
          "order_id": "string",
          "status": "string",
          "captured_amount": "number"
        }
      },
      {
        "name": "capture_payment",
        "description": "Capture an authorized credit-card payment (capturar un pago autorizado) that was created with capture=false. Use for hold-then-capture flows (e.g., authorize on order, capture on shipment). Optional p",
        "input": {
          "payment_id": "string",
          "amount_ars": "number? (partial capture)"
        },
        "output": {
          "payment_id": "string",
          "status": "approved",
          "amount": "number"
        }
      },
      {
        "name": "charge_saved_card",
        "description": "Charge a previously-saved card (cobrar con tarjeta guardada) for a returning customer. Requires customer_id + card_id (from list_customer_cards) AND a fresh CVV the user provides this session. AR Merc"
      },
      {
        "name": "compute_marketplace_fee",
        "description": "PURE HELPER (no network), given a transaction amount + fee rule (% or flat ARS, with optional min/max floors), returns the exact `marketplace_fee` value in ARS to pass to create_order or create_paymen"
      },
      {
        "name": "confirm_3ds_challenge",
        "description": "After the buyer completes a 3DS challenge (redirected back from challengeUrl), call this to poll MP and confirm whether the payment is now resolved. Polls get_payment up to N times with exponential ba"
      },
      {
        "name": "create_customer",
        "description": "Create a Mercado Pago customer record (crear cliente en Mercado Pago) so the buyer can save cards for future charges. Idempotent on email, if a customer with that email exists, MP returns it instead o",
        "input": {
          "email": "string",
          "first_name": "string?",
          "last_name": "string?",
          "identification": "{type: DNI|CUIT|CUIL, number: string}?"
        },
        "output": {
          "customer_id": "string",
          "email": "string",
          "first_name": "string|null",
          "last_name": "string|null",
          "date_created": "ISO"
        }
      },
      {
        "name": "create_customer_card",
        "description": "Add a saved card to an existing customer using a card_token (one-time token from MP frontend Cardform, agents should NEVER take raw card data, that's a PCI violation). Returns the saved CustomerCard w"
      },
      {
        "name": "create_order",
        "description": "Create a new Order via MP's modern Order Management API. DIFFERENT from create_payment_preference: Order is a transactional entity with explicit lifecycle (created → processed → captured/canceled), su",
        "input": {
          "type": "'online' | 'in_store'",
          "currency_id": "string? (default ARS)",
          "external_reference": "string?",
          "total_amount": "number?",
          "items": "array?",
          "payer_email": "string?",
          "capture_mode": "'automatic' | 'manual'?",
          "notification_url": "string?",
          "marketplace": "string?",
          "marketplace_fee": "number? (ARS)",
          "collector_id": "string|number? (seller MP user_id)"
        },
        "output": {
          "order_id": "string",
          "status": "string",
          "capture_mode": "string",
          "total_amount": "number"
        }
      },
      {
        "name": "create_payment",
        "description": "Create a one-time Mercado Pago payment (crear un pago, cobrar con Mercado Pago). Two flows: (a) with a card token from MP frontend Cardform, for transparent checkout; (b) without token, for non-card m",
        "input": {
          "amount_ars": "number positive",
          "payment_method_id": "string (visa | master | naranja | account_money | rapipago | ...)",
          "payer_email": "string (cannot equal seller email)",
          "token": "string | undefined (required for cards)",
          "installments": "number 1-24 | undefined",
          "external_reference": "string | undefined",
          "identification": "{type: DNI|CUIT|CUIL, number: string} | undefined"
        },
        "output": {
          "payment_id": "string",
          "status": "approved | pending | rejected | in_process | cancelled",
          "status_detail": "string (see AGENTS.md for recovery actions per value)",
          "amount": "number",
          "currency": "ARS",
          "installments": "number",
          "payment_method": "string",
          "external_reference": "string | null",
          "date_created": "ISO date",
          "date_approved": "ISO date | null"
        }
      },
      {
        "name": "create_payment_preference",
        "description": "Create a Mercado Pago Checkout Pro payment link (crear link de pago, cobrar por Mercado Pago) and get back a payment URL (init_point) to send to the customer. THIS is the recommended way for an agent ",
        "input": {
          "items": "array of {title, quantity, unit_price, description?, picture_url?}",
          "payer_email": "string?",
          "external_reference": "string?",
          "max_installments": "number 1-24?",
          "statement_descriptor": "string max 13 chars?",
          "excluded_payment_types": "array of (credit_card|debit_card|ticket|atm|bank_transfer)?"
        },
        "output": {
          "preference_id": "string",
          "init_point_url": "string (production)",
          "sandbox_init_point_url": "string (sandbox — use this if your token is TEST-)",
          "external_reference": "string | null",
          "next_step": "Send init_point_url to the customer..."
        }
      },
      {
        "name": "create_point_payment_intent",
        "description": "Create a payment intent on a physical Point device, the device prompts the buyer to tap/insert/swipe their card. Returns immediately with intent_id; query state via get_point_payment_intent or wait fo"
      },
      {
        "name": "create_pos",
        "description": "Create a POS (Point of Sale) under a store. The POS's external_id is what create_qr_payment uses. Each physical checkout / counter / agent typically has its own POS. Categories are MP-defined (default"
      },
      {
        "name": "create_qr_payment",
        "description": "Generate a dynamic in-store payment QR (cobrar con QR de Mercado Pago) for a buyer to scan with any AR wallet (Modo, BNA+, Cuenta DNI, Naranja X, Mercado Pago, etc., interop is mandated by Transferenc"
      },
      {
        "name": "create_store",
        "description": "Create a store under the seller's MP account. Stores are the parent entity for POSes (which generate QR payments). Required ONE-TIME setup before create_pos. Pass a unique external_id and a display na"
      },
      {
        "name": "create_subscription",
        "description": "Create a Mercado Pago recurring subscription (crear suscripción, cobro recurrente con Mercado Pago). Returns an init_point URL where the customer must complete the FIRST payment with their card and CV",
        "input": {
          "customer_email": "string (email; cannot equal seller email)",
          "amount_ars": "number (positive)",
          "frequency_months": "number (1-12)",
          "reason": "string (3-120 chars)",
          "external_reference": "string | undefined"
        },
        "output": {
          "subscription_id": "string",
          "status": "pending",
          "init_point_url": "string (URL the buyer must visit to complete first payment)",
          "next_step": "string (instructions for the agent)"
        }
      },
      {
        "name": "create_subscription_plan",
        "description": "Create a reusable subscription plan (crear plan de suscripción; preapproval_plan). Different from create_subscription: a plan defines price + frequency once, then customers subscribe to it via subscri"
      },
      {
        "name": "create_webhook",
        "description": "Subscribe a webhook URL to a MP topic (payment, subscription_authorized_payment, subscription_preapproval, merchant_order, point_integration_wh). MP will POST to this URL when events of that topic fir"
      },
      {
        "name": "delete_customer_card",
        "description": "Delete a saved card from a customer (eliminar tarjeta guardada). Common use: customer requests removal, or expired card cleanup. **IRREVERSIBLE, confirm with the user before calling. The customer must",
        "input": {
          "customer_id": "string",
          "card_id": "string"
        },
        "output": {
          "customer_id": "string",
          "card_id": "string",
          "deleted": "true"
        }
      },
      {
        "name": "delete_pos",
        "description": "Delete a POS. IRREVERSIBLE. Cancels any pending QR orders attached to it. Confirm with user before calling."
      },
      {
        "name": "delete_store",
        "description": "Delete a store. IRREVERSIBLE. Confirm with user before calling. Will fail if the store has associated POSes, delete those first."
      },
      {
        "name": "delete_webhook",
        "description": "Delete a webhook subscription. MP stops POSTing to it immediately. **IRREVERSIBLE, confirm before calling. State the webhook URL + topic so the user knows which subscription is being removed. Re-subsc"
      },
      {
        "name": "explain_payment_status",
        "description": "PURE HELPER (no network), given a Payment object (from get_payment / create_payment / handle_webhook), returns { summary, recommendedAction, final, paid, retryable } in Spanish. Translates MP's crypti"
      },
      {
        "name": "find_applicable_promos",
        "description": "PURE HELPER (no network, sub-ms), returns the 'cuotas sin interés' promotions applicable to a given (issuer, paymentMethodId, amount, category, date) tuple. Includes the federal Ahora 3/6/12/18/24/30 "
      },
      {
        "name": "find_customer_by_email",
        "description": "Find an existing Mercado Pago customer by email (buscar cliente por email). Returns the customer object if found, or null. Use before create_customer to avoid duplicate records.",
        "input": {
          "email": "string"
        },
        "output": {
          "found": "boolean",
          "customer_id": "string | null",
          "email": "string?",
          "first_name": "string?",
          "last_name": "string?"
        }
      },
      {
        "name": "get_account_balance",
        "description": "Get the seller's current MP wallet balance. Returns { available_balance, unavailable_balance, total_amount, currency_id }. The available balance is what the seller can withdraw or pay with right now; "
      },
      {
        "name": "get_account_info",
        "description": "Get info about the connected Mercado Pago account (información de la cuenta): site_id (MLA=Argentina), country_id, user_type (registered, partial, etc.). Useful to verify the agent is connected to the",
        "input": {},
        "output": {
          "account_id": "string",
          "email": "string|null",
          "nickname": "string|null",
          "country_id": "string|null (AR for Argentina)",
          "site_id": "string|null (MLA for Argentina)",
          "user_type": "string|null"
        }
      },
      {
        "name": "get_customer",
        "description": "Get a customer by id. Returns full Customer object: email, first_name, last_name, identification, address, default_card, registered cards. PURE READ. USE WHEN you have the customer_id from a previous "
      },
      {
        "name": "get_customer_card",
        "description": "Get details of a single saved card by (customer_id, card_id). Returns last 4 digits, expiration, brand, issuer. PURE READ, useful before charge_saved_card to confirm the card is still valid."
      },
      {
        "name": "get_dispute",
        "description": "Get details of a specific dispute including reason, amount, resolution status. Read-only."
      },
      {
        "name": "get_merchant_order",
        "description": "Get a merchant_order with all its associated payments + shipments. MerchantOrder is the parent entity for Payments associated with a single Preference, one Order can have multiple partial Payments (re"
      },
      {
        "name": "get_order",
        "description": "Fetch an Order by ID. Returns the Order with its lifecycle status and any attached payments/refunds.",
        "input": {
          "order_id": "string"
        },
        "output": "Order"
      },
      {
        "name": "get_payment",
        "description": "Fetch a Mercado Pago payment by ID (consultar un pago). Use to confirm status after webhook arrives, or to inspect details (status_detail explains rejections).",
        "input": {
          "payment_id": "string"
        },
        "output": "Same shape as create_payment output, plus net_received"
      },
      {
        "name": "get_payment_preference",
        "description": "Fetch a Checkout Pro preference / payment link by ID (consultar un link de pago). Returns the preference config and current init_point URLs. Use to inspect a previously-created link.",
        "input": {
          "preference_id": "string"
        },
        "output": "Same as create_payment_preference output, plus items array"
      },
      {
        "name": "get_point_payment_intent",
        "description": "Get the current state of a Point payment intent (OPEN, PROCESSING, FINISHED, CANCELED, ERROR). USE in polling loops if you can't wait for the webhook. When state=FINISHED, the intent.payment.id is the"
      },
      {
        "name": "get_pos",
        "description": "Fetch a POS by id. Returns: name, store_id, category, external_id, qr_template (if configured). PURE READ. Use when you need to find the external_id for create_qr_payment."
      },
      {
        "name": "get_refund",
        "description": "Fetch a single refund by (payment_id, refund_id). Returns the Refund object with amount, status, date_created. PURE READ, useful to verify a refund processed or to reconcile partial-refund history."
      },
      {
        "name": "get_settlement",
        "description": "Get details of a single settlement: amount, date_scheduled, date_processed, bank_account info (CBU + bank name)."
      },
      {
        "name": "get_store",
        "description": "Fetch a single store by (user_id, store_id). Returns store details: name, location, business_hours, external_id. PURE READ."
      },
      {
        "name": "get_subscription_plan",
        "description": "Fetch a subscription plan by id. Returns plan config: amount, frequency, status, init_point. Use to inspect a plan before subscribing customers, or to display plan details to the user."
      },
      {
        "name": "get_subscription_status",
        "description": "Check the status of a Mercado Pago subscription (consultar estado de una suscripción). Use this to confirm the customer completed the first payment (status becomes 'authorized') or to inspect the next",
        "input": {
          "subscription_id": "string (MP preapproval ID)"
        },
        "output": {
          "subscription_id": "string",
          "status": "pending | authorized | paused | cancelled",
          "payer_email": "string",
          "amount": "number",
          "currency": "ARS | USD | ...",
          "next_payment_date": "ISO date | null",
          "last_webhook_status": "string | null (cached from latest webhook)",
          "last_webhook_at": "ISO date | null"
        }
      },
      {
        "name": "get_test_cards",
        "description": "Pure helper that returns the official MP test cards for AR (MLA): VISA/Mastercard/Amex credit + debit, with the 'magic' holder names that route the payment to specific status_detail values (APRO=appro"
      },
      {
        "name": "handle_webhook",
        "description": "Process an incoming MP webhook in ONE call: verify the HMAC-SHA256 signature, parse the event, and (optionally) auto-fetch the underlying resource (Payment, Subscription, Order). Returns the structure",
        "input": {
          "raw_body": "string (raw JSON body — do NOT re-stringify)",
          "signature_header": "string|null (x-signature)",
          "request_id_header": "string|null (x-request-id)",
          "auto_fetch": "boolean? default true"
        },
        "output": {
          "verified": "boolean",
          "event": "{ topic, dataId, action, raw } | null",
          "resource": "Payment | Preapproval | null",
          "resource_error": "string | null",
          "error": "string | null"
        }
      },
      {
        "name": "list_account_movements",
        "description": "List wallet movements (incoming payments, transfers, refunds, holdings) for the active MP account. Filter by date range with `from`/`to` (ISO 8601). Useful for monthly conciliation or 'show me what ca"
      },
      {
        "name": "list_bank_accounts",
        "description": "List the bank accounts (CBUs) the seller has registered with MP for receiving payouts. Returns an array, the one with `is_default: true` is where settlements (release_money) go. USE BEFORE list_settle"
      },
      {
        "name": "list_customer_cards",
        "description": "List a customer's saved cards (listar tarjetas guardadas). Returns array with last 4 digits, expiration, payment method (visa, master, naranja, etc.). The card_id can be used in subsequent create_paym",
        "input": {
          "customer_id": "string"
        },
        "output": {
          "customer_id": "string",
          "count": "number",
          "cards": "array of {card_id, last_four_digits, expiration_month, expiration_year, payment_method, payment_method_name}"
        }
      },
      {
        "name": "list_identification_types",
        "description": "List valid identification types for the seller's site. AR returns: DNI, CI, LE, LC, Otro, Pasaporte, CUIT, CUIL with their min/max length. Useful to validate an identification before passing to create"
      },
      {
        "name": "list_issuers",
        "description": "List card issuers (banks) that support a payment_method_id. Optionally filter by `bin` (first 6 digits of the card) for accurate issuer detection. Useful with calculate_installments, issuer-specific p"
      },
      {
        "name": "list_payment_disputes",
        "description": "List all disputes / chargebacks raised against a payment. Read-only, resolution is dashboard-only. Surface the dashboard URL `https://www.mercadopago.com.ar/disputes/{dispute_id}` to the user when the"
      },
      {
        "name": "list_payment_methods",
        "description": "List the payment methods enabled for the seller's Mercado Pago account (medios de pago disponibles) (visa, master, naranja, naranja_x, cabal, account_money, rapipago, pagofacil, etc.). Use to validate",
        "input": {},
        "output": {
          "count": "number",
          "methods": "array of {id, name, payment_type, status, min_amount, max_amount}"
        }
      },
      {
        "name": "list_point_devices",
        "description": "List the physical Point devices (Smart, Tap to Pay, etc.) linked to the seller's MP account. Distinct from logical POS, these are actual terminals at brick-and-mortar shops. Returns each device's id ("
      },
      {
        "name": "list_pos",
        "description": "List all POSes for the seller (or filtered by store_id). Use to find an existing POS before create_qr_payment, or to surface options."
      },
      {
        "name": "list_refunds",
        "description": "List all refunds for a payment (listar reembolsos de un pago). Returns array of Refund objects. Useful to confirm a refund was processed or to inspect partial-refund history.",
        "input": {
          "payment_id": "string"
        },
        "output": {
          "payment_id": "string",
          "count": "number",
          "refunds": "array of {refund_id, amount, status, date_created}"
        }
      },
      {
        "name": "list_settlements",
        "description": "List settlements (release_money), i.e. transfers from the MP wallet to the seller's registered bank account (CBU). USE WHEN the user asks 'cuándo me deposita MP' or for monthly bank-conciliation repor"
      },
      {
        "name": "list_settlements_all",
        "description": "Collect ALL settlements matching a filter, auto-paginates. Pass `max_items` to cap. Use for monthly bank-conciliation reports."
      },
      {
        "name": "list_stores",
        "description": "List all stores configured for this MP account. Use this to find an existing store_id before create_pos, or to surface store options to the agent."
      },
      {
        "name": "list_subscription_payments",
        "description": "List the auto-charges under a subscription (cobros de una suscripción; authorized_payments). Useful for 'show me the cobros del último mes for this client' or to debug a failing recurring charge."
      },
      {
        "name": "list_subscription_plans",
        "description": "List all subscription plans defined for this MP account. Useful before create_subscription_plan to check if one already exists, or for surfacing options to a customer."
      },
      {
        "name": "list_webhooks",
        "description": "List all webhook subscriptions configured for this MP application. Use to see what topics + URLs are wired before adding new ones."
      },
      {
        "name": "mp_health_check",
        "description": "Liveness probe against MP. Returns { ok, latencyMs, userId, circuit }. USE THIS as the first call in long-running agent workflows to verify (a) network path to MP is up, (b) accessToken is valid, (c) "
      },
      {
        "name": "oauth_authorize_url",
        "description": "Build the URL the SELLER (third-party MP account) visits to authorize your marketplace app. Pass the seller's redirect uri (must be whitelisted in MP dev panel) and an opaque state token (CSRF protect",
        "input": {
          "redirect_uri": "string (must be whitelisted in MP dev panel)",
          "state": "string (CSRF token, bind to user session)"
        },
        "output": {
          "available": "boolean",
          "url": "string|null",
          "next_step": "string"
        }
      },
      {
        "name": "oauth_exchange_code",
        "description": "Exchange the authorization code (from the OAuth redirect) for an `OAuthToken`. Returns access_token, refresh_token, user_id, and expires_in. **PERSIST the entire response**, refresh_token is long-live",
        "input": {
          "code": "string",
          "redirect_uri": "string (must EXACTLY match the URL used in oauth_authorize_url)"
        },
        "output": {
          "available": "boolean",
          "token": "OAuthToken | null",
          "error": "string | null",
          "next_step": "string"
        }
      },
      {
        "name": "oauth_refresh_token",
        "description": "Refresh a per-seller access_token using the saved refresh_token. Call PROACTIVELY before expires_in elapses, or REACTIVELY on a 401 from a per-seller MercadoPagoClient. Returns a fresh OAuthToken, per",
        "input": {
          "refresh_token": "string"
        },
        "output": {
          "available": "boolean",
          "token": "OAuthToken | null",
          "error": "string | null"
        }
      },
      {
        "name": "pause_subscription",
        "description": "Pause an authorized Mercado Pago subscription (pausar suscripción). Charges stop until resumed. Only works on subscriptions in 'authorized' status.",
        "input": {
          "subscription_id": "string"
        },
        "output": {
          "subscription_id": "string",
          "status": "paused",
          "message": "string"
        }
      },
      {
        "name": "refund_payment",
        "description": "Refund an approved Mercado Pago payment (reembolsar un pago, hacer una devolución). Pass amount for partial refund; omit for full refund. Idempotency key is auto-generated based on paymentId+amount to",
        "input": {
          "payment_id": "string",
          "amount_ars": "number? (omit for full refund)"
        },
        "output": {
          "refund_id": "string",
          "payment_id": "string",
          "amount": "number",
          "status": "approved",
          "message": "string"
        }
      },
      {
        "name": "register_bank_account",
        "description": "Register a new bank account (CBU) for the seller. NOTE: MP usually requires this through the dashboard for compliance, this endpoint may not work for all accounts. If it fails with 403, redirect the u"
      },
      {
        "name": "resume_subscription",
        "description": "Resume a paused Mercado Pago subscription (reactivar suscripción). Charges resume on the next scheduled date. Only works on subscriptions in 'paused' status.",
        "input": {
          "subscription_id": "string"
        },
        "output": {
          "subscription_id": "string",
          "status": "authorized",
          "message": "string"
        }
      },
      {
        "name": "search_merchant_orders",
        "description": "Search merchant_orders by preference_id, external_reference, or status. Paginated. Returns up to 50 per page. USE WHEN you have a preference_id and want all its derived merchant_orders, or when reconc"
      },
      {
        "name": "search_payments",
        "description": "Search Mercado Pago payments with filters (buscar pagos). Most common: by external_reference (your-system identifier) to find all payments for an order, or by status='approved' to list successful char",
        "input": {
          "external_reference": "string?",
          "status": "string?",
          "payer_email": "string?",
          "begin_date": "ISO?",
          "end_date": "ISO?",
          "limit": "number 1-100, default 30",
          "offset": "number, default 0"
        },
        "output": {
          "total": "number",
          "returned": "number",
          "offset": "number",
          "payments": "array of {payment_id, status, amount, currency, payer_email, external_reference, date_created}"
        }
      },
      {
        "name": "search_payments_all",
        "description": "Collect ALL payments matching a filter, auto-paginates under the hood. Returns an array (NOT paginated) so the agent doesn't have to manage offset/limit loops manually. SAFETY: pass `max_items` to cap"
      },
      {
        "name": "search_subscriptions",
        "description": "Search subscriptions across the seller's account. Filter by status (pending/authorized/paused/cancelled), payer_email, external_reference, or preapproval_plan_id (to find all subscribers of a plan). P"
      },
      {
        "name": "subscribe_to_plan",
        "description": "Subscribe a customer to an existing plan (suscribir un cliente a un plan). Returns a Preapproval with init_point URL where the customer completes first payment. Cleaner than create_subscription when y"
      },
      {
        "name": "update_customer",
        "description": "Update a customer's profile (first_name, last_name, phone, identification, address, default_card). MP merges the patch, fields you don't send remain unchanged. Use to keep customer records in sync (e."
      },
      {
        "name": "update_merchant_order",
        "description": "Update a merchant_order, typically to add items or shipping info. Most agent flows don't need this; use only when integrating with a custom shipping flow that requires updating the MO mid-lifecycle."
      },
      {
        "name": "update_order",
        "description": "Patch an existing Order before it's captured/canceled. Common use: update items or external_reference.",
        "input": {
          "order_id": "string",
          "external_reference": "string?",
          "total_amount": "number?"
        },
        "output": "Order"
      },
      {
        "name": "update_payment_preference",
        "description": "Update a Checkout Pro preference (notification_url, back_urls, items, payer info, payment_methods exclusion list). Only works on preferences NOT yet paid. Common use: regenerate the link with a new no"
      },
      {
        "name": "update_point_device_mode",
        "description": "Switch a Point device's operating_mode between 'PDV' (bound to a logical POS, takes payments triggered through that POS) and 'STANDALONE' (works independently, accepts any payment). PDV is for cash-re"
      },
      {
        "name": "update_pos",
        "description": "Update a POS's properties (name, category, external_id). MP merges the patch."
      },
      {
        "name": "update_store",
        "description": "Update a store's properties (name, location, business_hours, external_id). MP merges the patch."
      },
      {
        "name": "update_subscription",
        "description": "Update a subscription's amount, status, reason, external_reference, OR card_token_id (to switch payment method when the buyer's card is expired/declined). For card swap: pass card_token_id from a fres"
      },
      {
        "name": "update_subscription_plan",
        "description": "Update a subscription plan's reason / amount / status / back_url. Existing customer subscriptions to the plan are NOT automatically updated, only NEW subscribers get the new pricing."
      },
      {
        "name": "update_webhook",
        "description": "Update a webhook's URL or topic. Useful when you change deployment URLs without resubscribing from scratch."
      },
      {
        "name": "validate_tax_id",
        "description": "PURE HELPER (no network, sub-ms), validates a tax ID against the appropriate country algorithm. Supports AR (DNI/CUIT/CUIL with modulo-11), BR (CPF/CNPJ with two-step weighted modulo), MX (RFC structu"
      }
    ],
    "name": "@ar-agents/mercadopago",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 89
    }
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/mi-argentina",
    "version": "0.1.0",
    "description": "Mi Argentina (gov OIDC) as drop-in tools for the Vercel AI SDK. PKCE login, ID-token JWT verification with JWKS caching, userinfo, refresh.",
    "tools": [
      {
        "name": "mi_argentina_start_login",
        "description": "Begin a Mi Argentina government login (iniciar sesión con Mi Argentina, OIDC). Returns an authorization URL the user must open in a browser, plus the OAuth `state` value the callback will return. SIDE"
      },
      {
        "name": "mi_argentina_complete_login",
        "description": "Complete a Mi Argentina login (completar el login de Mi Argentina) by exchanging the authorization code for tokens and verifying the ID token. Pass BOTH the `code` and `state` values that arrived in t"
      },
      {
        "name": "mi_argentina_get_user_profile",
        "description": "Fetch the Mi Argentina user profile (perfil del usuario de Mi Argentina) via the OIDC userinfo endpoint, given an access token already obtained from `mi_argentina_complete_login`. Returns sub, CUIL, D"
      },
      {
        "name": "mi_argentina_verify_id_token",
        "description": "Verify a Mi Argentina ID token (compact JWT) end-to-end: signature, issuer, audience, expiration. Returns the verified claims when valid; throws when invalid. USE THIS WHEN: you receive an ID token fr"
      },
      {
        "name": "mi_argentina_refresh_token",
        "description": "Exchange a refresh token for a new access token. Returns a new TokenResponse with refreshed access_token, id_token, and (per provider policy) a possibly-rotated refresh_token. USE THIS WHEN: an access"
      }
    ]
  },
  {
    "$schema": "https://ar-agents.ar/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/shipping",
    "version": "0.3.0",
    "description": "Argentine shipping carriers (Andreani, OCA, Correo Argentino) as drop-in tools for Vercel AI SDK 6+ agents.",
    "tools": [
      {
        "name": "cancelar_envio",
        "description": "Cancel a shipment that has not gone out for delivery (cancelar un envío). Returns { canceled: bool, reason? }. Si canceled=false, surface reason verbatim al usuario (típicamente 'ya está en reparto' o",
        "input": {
          "carrier?": "...",
          "tracking_number": "string"
        },
        "output": "CancelResult + { ok, available }"
      },
      {
        "name": "cotizar_envio",
        "description": "Quote the shipping cost with one carrier (cotizar un envío) (Andreani, OCA, o Correo Argentino). Pasá origen + destino + paquetes (peso + dimensiones + valor declarado) y servicio (standard, express, ",
        "input": {
          "carrier?": "andreani | oca | correo_argentino",
          "origin": "Address",
          "destination": "Address",
          "packages": "PackageInfo[]",
          "service?": "standard | express | same_day"
        },
        "output": "QuoteOption + { ok, available }"
      },
      {
        "name": "cotizar_envio_todos",
        "description": "Compare shipping quotes across ALL configured carriers in parallel (cotizar envío en todos los carriers). Returns { quotes: QuoteOption[] } ordenado por costo (más barato primero). USE WHEN el usuario",
        "input": {
          "origin": "Address",
          "destination": "Address",
          "packages": "PackageInfo[]",
          "service?": "..."
        },
        "output": "{ quotes: QuoteOption[], cheapest: QuoteOption, errors: { carrier, error }[] }"
      },
      {
        "name": "crear_envio",
        "description": "Create a real shipment and get a tracking number + label (crear un envío). RETURNS un trackingNumber + labelUrl + costo. SIDE EFFECT: el envío queda registrado en el sistema del carrier, confirma con ",
        "input": {
          "carrier?": "...",
          "origin": "Address",
          "destination": "Address",
          "packages": "PackageInfo[]",
          "service?": "...",
          "external_reference?": "string",
          "product_id?": "string (from cotizar_envio.productId to lock price)"
        },
        "output": "ShipmentCreated + { ok, available }"
      },
      {
        "name": "listar_sucursales",
        "description": "List carrier branch offices near a postal code (listar sucursales de un carrier) cerca de un Código Postal Argentino (CPA). Returns array con id, name, address, openingHours, distanceKm cuando disponi",
        "input": {
          "carrier?": "...",
          "postal_code": "string",
          "limit?": "number"
        },
        "output": "{ branches: Branch[], ok, available }"
      },
      {
        "name": "trackear_envio",
        "description": "Track a shipment by tracking number (trackear un envío, dónde está mi paquete). Returns { currentStatus, events[], deliveredAt? }. currentStatus normalizado a uno de: label_created, in_transit, out_fo",
        "input": {
          "carrier?": "...",
          "tracking_number": "string"
        },
        "output": "TrackingResult + { ok, available }"
      }
    ],
    "name": "@ar-agents/shipping",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 6
    }
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/sicore",
    "version": "0.1.0",
    "tools": [
      {
        "name": "sicore_calculate_retention",
        "description": "Calculate the SICORE income-tax retention on a supplier payment (calcular retención de Ganancias SICORE). Implements the RG 830/00 rule: retention is on the MONTHLY ACCUMULATED amount (passed via accu",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "sicore_calculate_retention_stream",
        "description": "Walk a chronological stream of payments to ONE supplier in ONE month and return the retention per payment, with the accumulator advancing automatically. Use this when reconciling a supplier's invoices",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "sicore_build_ddjj",
        "description": "Assemble the monthly SICORE return (armar la DDJJ SICORE) from a list of retention results. Returns totals + per-category + per-supplier breakdowns ready for filing. Pure aggregation; does NOT submit.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "sicore_submit_ddjj",
        "description": "Submit an assembled SICORE return to AFIP/ARCA (presentar la DDJJ SICORE). Throws SicoreUnconfiguredError unless the host wired a real submission adapter. Confirmation gate REQUIRED in the host UI bef",
        "sideEffects": "files tax return",
        "idempotent": true,
        "requiresConfirmation": true
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/suss",
    "version": "0.1.0",
    "tools": [
      {
        "name": "suss_calculate_employee_month",
        "description": "Calculate monthly payroll social-security amounts for one employee (calcular aportes y contribuciones) per F.931 / SICOSS. Returns the structured breakdown (jubilación, INSSJP, obra social, asignacion",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "suss_build_ddjj",
        "description": "Assemble the monthly SICOSS return (armar la DDJJ SICOSS, F.931) from per-employee results with vector totals (Seguridad Social, Obra Social, ART) + per-employee detail. Pure aggregation, does NOT sub",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "suss_submit_ddjj",
        "description": "Submit a SICOSS return to AFIP (presentar la DDJJ SICOSS, F.931). v0.1 ships only the contract, the real upload (fixed-width F.931 / SI.AP.RE web service) requires a custom adapter; throws SussUnconfi",
        "sideEffects": "files tax return",
        "idempotent": true,
        "requiresConfirmation": true
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/tienda-nube",
    "version": "0.1.0",
    "tools": [
      {
        "name": "tienda_nube_get_store",
        "description": "Get info about the Tienda Nube store (datos de la tienda) this adapter is bound to (denominación, currency, country, language, contact email).",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_list_products",
        "description": "List Tienda Nube products (listar productos de la tienda) with optional substring search + paginated results. Use `publishedOnly: true` to skip drafts. Returns `hasMore: true` when at least one more p",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_get_product",
        "description": "Get a Tienda Nube product by id (consultar un producto), including all variants.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_list_orders",
        "description": "List Tienda Nube orders (listar ventas, órdenes de la tienda) with status / payment_status / email filters + ISO 8601 date ranges. Reverse-chronological. The `paymentStatus: \"paid\"` filter is the typi",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_get_order",
        "description": "Get a Tienda Nube order by id (consultar una orden). Includes contact email + name + addresses + per-line products.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_list_customers",
        "description": "List Tienda Nube customers (listar clientes) with optional substring search across name + email.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_get_customer",
        "description": "Get a Tienda Nube customer by id (consultar un cliente), including default_address + total_spent.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_list_webhooks",
        "description": "List webhook subscriptions registered by this app for this store.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_create_webhook",
        "description": "Register a webhook subscription. URL must be https://. Common events: order/created, order/paid, order/fulfilled, product/updated, customer/created, app/uninstalled.",
        "sideEffects": "creates resource",
        "idempotent": false,
        "requiresConfirmation": false
      },
      {
        "name": "tienda_nube_delete_webhook",
        "description": "Delete a webhook subscription by id. Idempotent: deleting an unknown id resolves without raising.",
        "sideEffects": "irreversible",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/uala",
    "version": "0.2.0",
    "tools": [
      {
        "name": "uala_create_payment_link",
        "description": "Create a Ualá payment link (crear link de pago, cobrar con Ualá) the payer can complete on the web or via the Ualá app. Returns shareUrl + optional QR. Use for billing flows where the customer is not ",
        "sideEffects": "creates resource",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "uala_get_payment_link",
        "description": "Check a Ualá payment link's status (consultar estado de un link de pago) (status, paid amount, payer info if any). Use to poll a link's status if you don't yet have the webhook wired.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "uala_cancel_payment_link",
        "description": "Cancel an open Ualá payment link (cancelar un link de pago) so it can no longer be paid. Idempotent: cancelling an already-cancelled link is a no-op. Cannot un-cancel; create a new link instead.",
        "sideEffects": "irreversible",
        "idempotent": true,
        "requiresConfirmation": true
      },
      {
        "name": "uala_list_transactions",
        "description": "List Ualá account transactions (movimientos de la cuenta) in chronological order. Returns up to `limit` items + a `nextCursor` for paging. Use for reconciliation, agent-summarized statements, or match",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "uala_get_transaction",
        "description": "Fetch a single transaction by id. Use when you need full details (e.g. the externalReference or counterpart CUIT) that the list view trimmed.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "uala_get_balance",
        "description": "Get the current Ualá balance (consultar saldo): available + pending. Useful before initiating a payout to verify funds. Pass `currency` to query USD vs ARS independently.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "uala_create_payout",
        "description": "Send money from the Ualá account to a CBU (transferir dinero, hacer un payout). Status starts at `pending` and resolves to `paid` or `rejected`. IRREVERSIBLE once `paid`, agents calling this MUST gate",
        "sideEffects": "moves money",
        "idempotent": true,
        "requiresConfirmation": true
      },
      {
        "name": "uala_get_payout",
        "description": "Fetch the current state of a previously-created payout (status, paidAt, rejectionReason). Use to poll payout completion when you don't yet have a webhook wired.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://ar-agents.dev/schemas/tools.manifest.v1.json",
    "package": "@ar-agents/whatsapp",
    "version": "0.5.0",
    "tools": [
      {
        "name": "mark_whatsapp_read"
      },
      {
        "name": "send_whatsapp_buttons"
      },
      {
        "name": "send_whatsapp_list"
      },
      {
        "name": "send_whatsapp_media"
      },
      {
        "name": "send_whatsapp_template"
      },
      {
        "name": "send_whatsapp_text"
      }
    ],
    "adapters": [
      {
        "name": "WhatsAppClient",
        "kind": "transport",
        "purpose": "HTTP client over Meta Graph API for WhatsApp Cloud."
      }
    ],
    "webhooks": [
      {
        "name": "parseWebhookEvent",
        "purpose": "Parse Meta's nested webhook envelope into a normalized event (single)."
      },
      {
        "name": "parseWebhookEvents",
        "purpose": "Parse all events from a batched webhook payload (Meta can send 3+ status updates per POST)."
      },
      {
        "name": "verifyWebhookSignature",
        "purpose": "HMAC-SHA256 verification of X-Hub-Signature-256 header. Pass RAW body."
      },
      {
        "name": "verifyWebhookSubscription",
        "purpose": "Handle Meta's GET handshake with hub.challenge / hub.verify_token."
      }
    ],
    "errors": [
      "WhatsAppError",
      "WhatsAppNotConfiguredError",
      "WhatsAppApiError",
      "WhatsAppRecipientNotOnPlatformError",
      "WhatsAppOutsideWindowError",
      "WhatsAppWebhookSignatureError"
    ],
    "name": "@ar-agents/whatsapp",
    "meta": {
      "generated_by": "scripts/regen-manifests.mjs",
      "tool_count": 6
    }
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/wscdc",
    "version": "0.1.0",
    "tools": [
      {
        "name": "wscdc_validate_comprobante",
        "description": "Verify a received invoice's CAE against AFIP (constatar comprobante, verificar CAE de una factura recibida): confirms it was actually issued by AFIP. Use this BEFORE ingesting any received factura int",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "wscdc_health",
        "description": "Ping the AFIP WSCDC service (Dummy operation). Returns AppServer/DbServer/AuthServer statuses. Use to confirm WSCDC is reachable + your WSAA token still works before a batch validation flow.",
        "sideEffects": "network read",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  },
  {
    "$schema": "https://agents.md/tools.manifest.schema.json",
    "package": "@ar-agents/x402",
    "version": "0.1.0",
    "tools": [
      {
        "name": "x402_get_payment_requirements",
        "description": "Probe x402 payment requirements for a URL without paying.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      },
      {
        "name": "x402_paid_fetch",
        "description": "Pay for an HTTP 402 resource and fetch it via the x402 protocol.",
        "sideEffects": "moves money",
        "idempotent": false,
        "requiresConfirmation": true
      },
      {
        "name": "x402_verify_payment",
        "description": "Verify an x402 payment authorization as a seller via the facilitator.",
        "sideEffects": "none",
        "idempotent": true,
        "requiresConfirmation": false
      }
    ]
  }
] as const;
